language: node_js
node_js:
  - "10"

cache: npm

git:
  depth: 1

before_script:
  - npm run build

script:
  - npm run lint -- --no-fix
  - npm run test:unit -- --ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
    branch: master
